version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: install requirements
          command: pip install --no-cache-dir --upgrade -r requirements.txt
      - run:
          name: pytest
          command: pytest
  lint:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: install requirements
          command: pip install --no-cache-dir --upgrade -r requirements.txt
      - run:
          name: flake8
          command: flake8
  push_to_docker_hub:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: authentification to docker hub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build docker image
          command: docker build -t nobimeromeo/python-oc-lettings:main .
      - run:
          name: push docker image
          command: docker push nobimeromeo/python-oc-lettings:main

workflows:
  version: 2.1
  deploy:
    jobs:
      - test
      - lint
      - push_to_docker_hub:
          requires:
            - test
            - lint
