version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: install requirements
          command: pip install --no-cache-dir --upgrade -r requirements.txt

  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: pytest
          command: pytest
